// GENERATED by scripts/build_html.py -- do not edit.
// Cache-first service worker so the app opens instantly and works with no
// signal at the park. VERSION changes whenever any precached file changes.
const VERSION = "46c96db7a1f3";
const CACHE = "fc-" + VERSION;
const PRECACHE = [
  "./",
  "index.html",
  "assets/app.js?v=ec992f01009e",
  "manifest.webmanifest",
  "assets/fonts/barlow-latin-400-normal.woff2",
  "assets/fonts/barlow-latin-500-normal.woff2",
  "assets/fonts/barlow-latin-600-normal.woff2",
  "assets/fonts/barlow-condensed-latin-600-normal.woff2",
  "assets/fonts/barlow-condensed-latin-700-normal.woff2",
  "assets/fonts/barlow-condensed-latin-800-normal.woff2",
  "icons/icon-192.png?v=226072e0",
  "icons/icon-512.png?v=dd565094",
  "icons/icon-maskable-512.png?v=dd565094",
  "icons/apple-touch-icon.png?v=9768eb68",
  "icons/favicon-32.png?v=eb760835"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(PRECACHE.map((u) => new Request(u, { cache: "reload" }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("fc-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  const path = new URL(req.url).pathname;
  if (req.mode === "navigate") {
    // App shell (./ or index.html): always the cached index.html, offline-first.
    // Any other page (e.g. sandbox.html on a local dev server) goes to the network.
    if (path.endsWith("/") || path.endsWith("/index.html")) event.respondWith(caches.match("index.html").then((r) => r || fetch(req)));
    return;
  }
  event.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && res.type === "basic") {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    }))
  );
});
